name: Deploy to cPanel
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.9.0'
          
      - name: Install NPM Dependencies & Build Assets
        run: |
          npm install
          npm run build
          
      - name: Generate Application Key
        run: php artisan key:generate --force
        
      - name: Cache Config
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_ROOT_DIR }}/
          log-level: verbose